### ISSUE TITLE
Question about "test_simple_add_schedule" and "test_do_not_add_schedule_if_stops_are_not_connected"public test

### ISSUE THREAD

**Issue by madarasibalazs** [IMC-UAS-Krems/2024-DBST2VO-Public#23]
@alessiogambi 

The problem is, that in both tests you are trying to add a train with a train_key = None. We cannot change the tests, and there is no "nice" way to work around that. 
Therefore, we are suggesting a small change in both tests. Instead of:
```
train_key = None
t.add_train(train_key, train_capacity=100, train_status=TrainStatus.OPERATIONAL)
```    

We would suggest the following:
```
train_key = t.add_train(None, train_capacity=100, train_status=TrainStatus.OPERATIONAL)
```    
This keeps the train key being None, but allows us implement a solution to change it and not pass it to the add_station function as a None parameter.

**Comment by alessiogambi** [comment]
@madarasibalazs Actually, there are various solutions to this problem, including define you own key logic to deal with None or use autoincrement ID (see for instance, [https://mariadb.com/kb/en/auto_increment/](https://mariadb.com/kb/en/auto_increment/) or [https://stackoverflow.com/questions/61349754/how-to-generate-autoincrement-guid-on-insert-without-triggers-and-manual-inserts](https://stackoverflow.com/questions/61349754/how-to-generate-autoincrement-guid-on-insert-without-triggers-and-manual-inserts)])

The reason why the tests do not provide any key is that we cannot speculate which key will you be using (int, string, etc.)

**Comment by dfoddav2** [comment]
@alessiogambi
I think the problem here is rather that in `test_simple_add_schedule` we first initialize the `train_key` to `None`, which we can handle on server side by as you said autoincrementing, or what I chose to do was UUID.

```Python
    # Add a train
    train_key = None
    t.add_train(train_key, train_capacity=100, train_status=TrainStatus.OPERATIONAL)
```

But later in the function we are using the same previously defined `train_key` of `None` to add the schedule.

```Python
    t.add_schedule(
                train_key,
                starting_hours_24_h, starting_minutes,
                stops,
                valid_from_day, valid_from_month, valid_from_year,
                valid_until_day, valid_until_month, valid_until_year)
```

Even if we used autoincrement / UUID for the creation of the train, the freshly created Train wouldn't be matched when adding the schedule.

The same holds true for `test_do_not_add_schedule_if_stops_are_not_connected`.

**Comment by Samolet0489** [comment]
Hey, me and @madarasibalazs  found a work around on this. Thanks.

**Comment by alessiogambi** [comment]
This has been fixed by letting `add_train` (and `add_train_station`) return a TraitsKey
